# Generated by Django 4.2.3 on 2023-07-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100, verbose_name='Amount')),
                ('order_id', models.CharField(max_length=100, verbose_name='Order ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='Payment ID')),
                ('signature', models.CharField(max_length=100, verbose_name='Signature')),
            ],
        ),
    ]
